### PR TITLE
Highlight last selected facet

### PR DESCRIPTION
**Pull request by heemayl**

### CODE REVIEW

**Comment by heemayl** [comment]
@mroswell The highlighted background color can be changed from here (if needed): https://github.com/heemayl/list-N/blob/highlight-last-selected-facet/static/css/styles.css#L76

**Comment by mroswell** [comment]
Re: color, animation time, and selection: (so it's not so overwhelming)

```
@keyframes highlight-fade {
    0% {
	Background: #cde7dd;
    }
    100% {
	Background: none;
    }
}

.fade-bg > p {
    animation: highlight-fade 1s;
}

```
But the unexpected issues here are:
1) The color flashes even if we visit via  permalink.
2) the color flashes on a different open facet after another facet is closed and returned back to the suggested facets list

Is there any solution to that? Maybe it somehow depends on a click actually happening in the suggested_facets...

**Comment by heemayl** [comment]
@mroswell Code is updated to use a session cookie (`latest_selected_facet`) set/reset on the `click` events on the suggested facets to handle the issues mentioned (dropping the extraction from the Datasette query string). 

We could in theory use a separate query string but didn't use it to encode this info as Datasette is dependent heavily on the query string to do its filtering and such, so just being cautious not to break anything as I don't know (yet) how everything is implemented underneath.

**Comment by mroswell** [comment]
Thank you!

**Pull request merged**
